POST http://localhost:8080/workDays/1/menu
Content-Type: application/json

{
  "menuName": "이제까지이런맛은없었다이것은갈비인가통닭인가"
}

###

POST http://localhost:8080/workDays/1/menu
Content-Type: application/json

{
  "menuName": "밥"
}

###

POST http://localhost:8080/workDays/1/menu
Content-Type: application/json

{
  "menuName": "오징어볶음",
  "pos": 65535
}

###